comment:
  layout: "condensed_header, reach, diff, components, condensed_files, condensed_footer"
  require_changes: true
  branches:
    - main

coverage:
  range: 60..100
  status:
    project:
      default:
        target: 85%
        threshold: 0%
      delta:
        target: auto
        informational: true

github_checks:
  annotations: false
